# Generated by Django 3.0.4 on 2020-05-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa'),
        ),
        migrations.AddField(
            model_name='subdetalle',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Detalle'),
        ),
        migrations.AddField(
            model_name='subcategoriaarticulo',
            name='hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_hijo', to='articulos.CategoriaArticulo'),
        ),
        migrations.AddField(
            model_name='subcategoriaarticulo',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categorias', to='articulos.CategoriaArticulo'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.ChatArticulo'),
        ),
        migrations.AddField(
            model_name='fototienda',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='articulos.Tienda'),
        ),
        migrations.AddField(
            model_name='fotoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo'),
        ),
        migrations.AddField(
            model_name='chatarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo'),
        ),
        migrations.AddField(
            model_name='chatarticulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.Tienda'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoriaarticulo',
            unique_together={('hijo', 'padre')},
        ),
    ]
