# Generated by Django 3.0.4 on 2020-05-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20200506_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='nombre',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='subdetalle',
            old_name='nombre',
            new_name='valor',
        ),
    ]
