# Generated by Django 3.0.4 on 2020-05-13 21:58

import apps.empresa.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria_empresa',
                'verbose_name_plural': 'Categorias de una Empresa',
                'db_table': 'CATEGORIA_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.CategoriaEmpresa')),
                ('empresario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=1, max_digits=7)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('E', 'En Curso'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='N', max_length=1)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Zona')),
                ('telefono', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('hora_inicio', models.TimeField(blank=True, default='15:00:00')),
                ('hora_fin', models.TimeField(blank=True, default='15:00:00')),
                ('disponible', models.BooleanField(blank=True, default=False)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('foto', models.ImageField(blank=True, default='sucursal/no-img.jpg', help_text='El tamaño maximo para las fotos es 3 Megas', null=True, upload_to='sucursal/', validators=[apps.empresa.validators.tamaño_del_archivo])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'SUCURSAL',
            },
        ),
        migrations.CreateModel(
            name='ProductoFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=1, max_digits=7)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('foto', models.ImageField(blank=True, default='productos/no-img.jpg', null=True, upload_to='productos/')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Sucursal')),
            ],
            options={
                'verbose_name': 'producto_final',
                'verbose_name_plural': 'productos_final',
                'db_table': 'PRODUCTO_FINAL',
            },
        ),
        migrations.CreateModel(
            name='PedidoProductoFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[apps.empresa.validators.cantidad_min_value, apps.empresa.validators.cantidad_max_value])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Pedido')),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.ProductoFinal')),
            ],
            options={
                'verbose_name': 'pedido_producto',
                'verbose_name_plural': 'pedido_productos',
                'db_table': 'PEDIDO_PRODUCTO',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Sucursal'),
        ),
        migrations.CreateModel(
            name='Chat_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=14)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Pedido')),
            ],
            options={
                'verbose_name': 'chat_pedido',
                'verbose_name_plural': 'chat_pedidos',
                'db_table': 'CHAT_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[apps.empresa.validators.cantidad_min_value, apps.empresa.validators.cantidad_max_value])),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo', to='empresa.ProductoFinal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto', to='empresa.ProductoFinal')),
            ],
            options={
                'verbose_name': 'combo',
                'verbose_name_plural': 'combos',
                'db_table': 'COMBO',
                'unique_together': {('combo', 'producto')},
            },
        ),
    ]
