# Generated by Django 3.0.4 on 2020-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='disponible',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
