# Generated by Django 3.0.4 on 2020-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_sucursal_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
