# Generated by Django 3.0.4 on 2020-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_sucursal_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
